# Generated by Django 2.2.6 on 2019-10-14 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daintegrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='secrets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dacore.SecretsCollection'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
