# Generated by Django 2.2.6 on 2019-10-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daintegrations', '0002_auto_20191014_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='secrets',
            field=models.SlugField(choices=[('DJANGO_SECRETS', 'DJANGO_SECRETS'), ('DATABASE_SECRETS', 'DATABASE_SECRETS'), ('ORISHIKU_TWITTER_SECRETS', 'ORISHIKU_TWITTER_SECRETS')], unique=True),
        ),
    ]
