# Generated by Django 2.2.6 on 2019-10-14 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daintegrations', '0003_auto_20191014_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('twitter', 'Twitter')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('type', 'user')},
        ),
    ]
